/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$map.d.ts#1643820505045
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Wrappable, IterableIterator } from '../../types/iterable';

declare function map<O, T>(
  func: (value: T, i: number) => O,
): (source: Wrappable<T>) => IterableIterator<O>;

declare function map<O, T>(
  func: (value: T, i: number) => O,
  source: Wrappable<T>,
): IterableIterator<O>;

export { map };
