/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$includes-any.d.ts#1643820505040
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncWrappable } from '../../types/async-iterable';

declare function asyncIncludesAny(
  same: (a: any, b: any) => boolean,
  values: Array<any>,
): (iterable: AsyncWrappable<any>) => Promise<boolean>;

declare function asyncIncludesAny(
  same: (a: any, b: any) => boolean,
  values: Array<any>,
  iterable: AsyncWrappable<any>,
): Promise<boolean>;

declare function asyncIncludesAny(
  values: Array<any>,
  iterable: AsyncWrappable<any>,
): Promise<boolean>;

export { asyncIncludesAny };
