/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$includes-any.d.ts#1643820505040
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Wrappable } from '../../types/iterable';

declare function includesAny(
  same: (a: any, b: any) => boolean,
  values: Array<any>,
): (iterable: Wrappable<any>) => boolean;

declare function includesAny(
  same: (a: any, b: any) => boolean,
  values: Array<any>,
  iterable: Wrappable<any>,
): boolean;

declare function includesAny(values: Array<any>, iterable: Wrappable<any>): boolean;

export { includesAny };
