/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/array-from-async/array-from-async.d.ts#1643820505062
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { arrayFromAsync as default } from '../impls/array-from-async/array-from-async';
