/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/array-last-or/array-last-or.d.ts#1643820505063
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { arrayLastOr as default } from '../impls/array-last-or/array-last-or';
