/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/$split-on-any-seq/async-split-on-any-seq.d.ts#1643820541706
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { asyncSplitOnAnySeq as default } from '../impls/$split-on-any-seq/async-split-on-any-seq';
