/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/$wrap/async-wrap.js#1643820542025
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { asyncWrap as default } from '../impls/$wrap/async-wrap.js';
