/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/$split-when/async-split-when.d.ts#1643820542285
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { asyncSplitWhen as default } from '../impls/$split-when/async-split-when';
