/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/$enumerate/async-enumerate.d.ts#1643820542777
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { asyncEnumerate as default } from '../impls/$enumerate/async-enumerate';
