/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/$spliterate-grouped/async-spliterate-grouped.d.ts#1643820544069
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { asyncSpliterateGrouped as default } from '../impls/$spliterate-grouped/async-spliterate-grouped';
