/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/$cycle-times/cycle-times.d.ts#1643820543671
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { cycleTimes as default } from '../impls/$cycle-times/cycle-times';
