/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/$flat-map/flat-map.js#1643820543635
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { flatMap as default } from '../impls/$flat-map/flat-map.js';
