/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/$forkerate/forkerate.d.ts#1643820543002
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { forkerate as default } from '../impls/$forkerate/forkerate';
