/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/$includes-any-seq/includes-any-seq.js#1643820542651
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { includesAnySeq as default } from '../impls/$includes-any-seq/includes-any-seq.js';
