/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/is-async-wrappable/is-async-wrappable.d.ts#1643820505069
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { isAsyncWrappable as default } from '../impls/is-async-wrappable/is-async-wrappable';
