/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/$is-empty/is-empty.d.ts#1643820542808
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { isEmpty as default } from '../impls/$is-empty/is-empty';
