/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/is-loopable/is-loopable.d.ts#1643820505069
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { isLoopable as default } from '../impls/is-loopable/is-loopable';
