/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/$join-with/join-with.d.ts#1643820542172
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { joinWith as default } from '../impls/$join-with/join-with';
