/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/object-keys/object-keys.js#1643820505079
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { objectKeys as default } from '../impls/object-keys/object-keys.js';
