/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/$peekerate/peekerate.d.ts#1643820542831
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { peekerate as default } from '../impls/$peekerate/peekerate';
