/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/$split-groups/split-groups.js#1643820542741
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { splitGroups as default } from '../impls/$split-groups/split-groups.js';
