/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/$spliterate-grouped/spliterate-grouped.js#1643820544084
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { spliterateGrouped as default } from '../impls/$spliterate-grouped/spliterate-grouped.js';
