/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/$starts-with/starts-with.d.ts#1643820541848
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { startsWith as default } from '../impls/$starts-with/starts-with';
