/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/wrap-values/wrap-values.js#1643820505083
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { wrapValues as default } from '../impls/wrap-values/wrap-values.js';
