/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/wrap-entries/wrap-entries.d.ts#1643820505082
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { wrapEntries as default } from '../impls/wrap-entries/wrap-entries';
