/* @macrome
 * @generatedby /generate/generators/methods-links/index.cjs
 * @generatedfrom ../impls/wrap-keys/wrap-keys.js#1643820505082
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { wrapKeys as default } from '../impls/wrap-keys/wrap-keys.js';
