/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$spliterate-grouped.d.ts#1643820505051
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
declare function asyncSpliterateGrouped(...args: Array<any>): any;

declare const split: symbol;

export { split };

export { asyncSpliterateGrouped };
