/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$split-on-seq.d.ts#1643820505050
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncWrappable, AsyncIterableIterator } from '../../types/async-iterable';

declare function asyncSplitOnSeq(
  same: (a: any, b: any) => boolean,
  separatorSeq: AsyncWrappable<any>,
): <T>(source: AsyncWrappable<T>) => AsyncIterableIterator<AsyncIterableIterator<T>>;

declare function asyncSplitOnSeq<T>(
  same: (a: any, b: any) => boolean,
  separatorSeq: AsyncWrappable<any>,
  source: AsyncWrappable<T>,
): AsyncIterableIterator<AsyncIterableIterator<T>>;

declare function asyncSplitOnSeq<T>(
  separatorSeq: AsyncWrappable<any>,
  source: AsyncWrappable<T>,
): AsyncIterableIterator<AsyncIterableIterator<T>>;

export { asyncSplitOnSeq };
