/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$fork.d.ts#1643820505039
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { IterableIterator as SyncIterableIterator } from '../../types/iterable';
import { AsyncWrappable, AsyncSingletonIterableIterator } from '../../types/async-iterable';

declare function asyncFork<T>(
  source: AsyncWrappable<T>,
): SyncIterableIterator<AsyncSingletonIterableIterator<T>>;

export { asyncFork };
