/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$split.d.ts#1643820505051
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import {
  IterableIterator as SyncIterableIterator,
  Wrappable,
  IterableIterator,
} from '../../types/iterable';

declare function split<T>(source: Wrappable<T>): IterableIterator<SyncIterableIterator<T>>;

export { split };
