/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$take-while.d.ts#1643820505056
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncWrappable, AsyncIterableIterator } from '../../types/async-iterable';

declare function asyncTakeWhile<T>(
  predicate: (value: T, i: number) => boolean | Promise<boolean>,
): (source: AsyncWrappable<T>) => AsyncIterableIterator<T>;

declare function asyncTakeWhile<T>(
  predicate: (value: T, i: number) => boolean | Promise<boolean>,
  source: AsyncWrappable<T>,
): AsyncIterableIterator<T>;

export { asyncTakeWhile };
