/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$interpose.d.ts#1643820505043
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Wrappable, IterableIterator } from '../../types/iterable';

declare function interpose<V>(value: V): <T>(source: Wrappable<T>) => IterableIterator<T | V>;

declare function interpose<V, T>(value: V, source: Wrappable<T>): IterableIterator<T | V>;

export { interpose };
