/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$take-sorted.d.ts#1643820505055
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncWrappable, AsyncIterableIterator } from '../../types/async-iterable';

declare function asyncTakeSorted<T>(iterable: AsyncWrappable<T>): AsyncIterableIterator<T>;

declare function asyncTakeSorted<T>(
  n: number,
): (source: AsyncWrappable<T>) => AsyncIterableIterator<T>;

declare function asyncTakeSorted<T>(
  n: number,
  compare: (a: T, b: T) => number,
): (source: AsyncWrappable<T>) => AsyncIterableIterator<T>;

declare function asyncTakeSorted<T>(
  compare: (a: T, b: T) => number,
): (source: AsyncWrappable<T>) => AsyncIterableIterator<T>;

declare function asyncTakeSorted<T>(n: number, source: AsyncWrappable<T>): AsyncIterableIterator<T>;

declare function asyncTakeSorted<T>(
  n: number,
  compare: (a: T, b: T) => number,
  source: AsyncWrappable<T>,
): AsyncIterableIterator<T>;

declare function asyncTakeSorted<T>(
  compare: (a: T, b: T) => number,
  source: AsyncWrappable<T>,
): AsyncIterableIterator<T>;

export { asyncTakeSorted };
