/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$append.d.ts#1643820505027
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncWrappable, AsyncIterableIterator } from '../../types/async-iterable';

declare function asyncAppend<T, V>(
  value: V,
  source: AsyncWrappable<T>,
): AsyncIterableIterator<V | T>;

declare function asyncAppend<V>(
  value: V,
): <T>(source: AsyncWrappable<T>) => AsyncIterableIterator<V | T>;

export { asyncAppend };
