/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$str.d.ts#1643820505054
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncWrappable } from '../../types/async-iterable';

declare function asyncStr(strings: AsyncWrappable<string>): Promise<string>;

declare function asyncStr(strings: AsyncWrappable<{ toString(): string }>): Promise<string>;

export { asyncStr };
