/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$take.js#1643820505056
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { asyncIterableCurry } from '../../internal/async-iterable.js';

export async function* __asyncTake(iterable, n) {
  let i = 0;
  for await (const value of iterable) {
    if (i++ === n) break;
    yield value;
  }
}

export const asyncTake = /*#__PURE__*/ asyncIterableCurry(__asyncTake);
