/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$take.js#1643820505056
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { iterableCurry } from '../../internal/iterable.js';

export function* __take(iterable, n) {
  let i = 0;
  for (const value of iterable) {
    if (i++ === n) break;
    yield value;
  }
}

export const take = /*#__PURE__*/ iterableCurry(__take);
