/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$find-or.d.ts#1643820505036
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Wrappable } from '../../types/iterable';

declare function findOr<N, T, S extends T>(
  notFoundValue: N,
  predicate: (value: T, i: number) => value is S,
): (iterable: Wrappable<T>) => S | N;

declare function findOr<N, T>(
  notFoundValue: N,
  predicate: (value: T, i: number) => boolean,
): (iterable: Wrappable<T>) => T | N;

declare function findOr<N, T, S extends T>(
  notFoundValue: N,
  predicate: (value: T, i: number) => value is S,
  iterable: Wrappable<T>,
): S | N;

declare function findOr<N, T>(
  notFoundValue: N,
  predicate: (value: T, i: number) => boolean,
  iterable: Wrappable<T>,
): T | N;

export { findOr };
