/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$starts-with-seq.d.ts#1643820505053
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Wrappable } from '../../types/iterable';

declare function startsWithSeq(
  same: (a: any, b: any) => boolean,
  seq: Wrappable<any>,
): (iterable: Wrappable<any>) => boolean;

declare function startsWithSeq(
  same: (a: any, b: any) => boolean,
  seq: Wrappable<any>,
  iterable: Wrappable<any>,
): boolean;

declare function startsWithSeq(seq: Wrappable<any>, iterable: Wrappable<any>): boolean;

export { startsWithSeq };
