/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$find-or.spec.ts#1643820505036
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import assert from 'static-type-assert';
import { AsyncIterable } from '../../../types/async-iterable';
import { asyncFindOr } from 'iter-tools-es';

declare const Ø: never;

assert<Promise<number | 0>>(
  asyncFindOr(Ø as 0, Ø as (value: number) => any, Ø as AsyncIterable<number>),
);

assert<Promise<2 | 0>>(
  asyncFindOr(Ø as 0, Ø as (value: number) => value is 2, Ø as AsyncIterable<number>),
);
