/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$find-or.spec.ts#1643820505036
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import assert from 'static-type-assert';
import { Iterable } from '../../../types/iterable';
import { findOr } from 'iter-tools-es';

declare const Ø: never;

assert<number | 0>(findOr(Ø as 0, Ø as (value: number) => any, Ø as Iterable<number>));

assert<2 | 0>(findOr(Ø as 0, Ø as (value: number) => value is 2, Ø as Iterable<number>));
