/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$collate.d.ts#1643820505029
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Wrappable, IterableIterator } from '../../types/iterable';

declare function collate<T>(...sources: Array<Wrappable<T>>): IterableIterator<T>;

declare function collate<T>(
  compare: (a: T, b: T) => number,
  ...sources: Array<Wrappable<T>>
): IterableIterator<T>;

declare function collate<T>(
  compare: (a: T, b: T) => number,
): (...sources: Array<Wrappable<T>>) => IterableIterator<T>;

export { collate };
