/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$split-on-any-seq.d.ts#1643820505049
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Wrappable, IterableIterator } from '../../types/iterable';

declare function splitOnAnySeq(
  same: (a: any, b: any) => boolean,
  separatorSeqs: Array<Wrappable<any>>,
): <T>(source: Wrappable<T>) => IterableIterator<IterableIterator<T>>;

declare function splitOnAnySeq<T>(
  same: (a: any, b: any) => boolean,
  separatorSeqs: Array<Wrappable<any>>,
  source: Wrappable<T>,
): IterableIterator<IterableIterator<T>>;

declare function splitOnAnySeq<T>(
  separatorSeqs: Array<Wrappable<any>>,
  source: Wrappable<T>,
): IterableIterator<IterableIterator<T>>;

export { splitOnAnySeq };
