/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$interleave.d.ts#1643820505041
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
declare function interleave(...args: Array<any>): any;

export { interleave };
