/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$includes.d.ts#1643820505041
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Wrappable } from '../../types/iterable';

declare function includes(
  same: (a: any, b: any) => boolean,
  value: any,
): (iterable: Wrappable<any>) => boolean;

declare function includes(
  same: (a: any, b: any) => boolean,
  value: any,
  iterable: Wrappable<any>,
): boolean;

declare function includes(value: any, iterable: Wrappable<any>): boolean;

export { includes };
