/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$every.d.ts#1643820505035
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncWrappable } from '../../types/async-iterable';

declare function asyncEvery<T>(
  predicate: (value: T) => boolean | Promise<boolean>,
): (iterable: AsyncWrappable<T>) => Promise<boolean>;

declare function asyncEvery<T>(
  predicate: (value: T) => boolean | Promise<boolean>,
  iterable: AsyncWrappable<T>,
): Promise<boolean>;

export { asyncEvery };
