/* @macrome
 * @generatedby /generate/generators/__methods-links/index.cjs
 * @generatedfrom ../impls/$filter/async-filter.js#1643820542326
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { __asyncFilter as default } from '../impls/$filter/async-filter.js';
