/* @macrome
 * @generatedby /generate/generators/__methods-links/index.cjs
 * @generatedfrom ../impls/$drop-while/drop-while.js#1643820544017
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { __dropWhile as default } from '../impls/$drop-while/drop-while.js';
