/* @macrome
 * @generatedby /generate/generators/__methods-links/index.cjs
 * @generatedfrom ../impls/object-values/object-values.js#1643820505079
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { __objectValues as default } from '../impls/object-values/object-values.js';
