/* @macrome
 * @generatedby /generate/generators/__methods-links/index.cjs
 * @generatedfrom ../impls/$round-robin/round-robin.js#1643820542689
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { __roundRobin as default } from '../impls/$round-robin/round-robin.js';
