/* @macrome
 * @generatedby /generate/generators/__methods-links/index.cjs
 * @generatedfrom ../impls/$split-on-seq/split-on-seq.js#1643820543760
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { __splitOnSeq as default } from '../impls/$split-on-seq/split-on-seq.js';
