/* @macrome
 * @generatedby /generate/generators/__methods-links/index.cjs
 * @generatedfrom ../impls/$split-on-any/split-on-any.js#1643820541979
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
export { __splitOnAny as default } from '../impls/$split-on-any/split-on-any.js';
