/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$take-last.d.ts#1643820505055
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncWrappable } from '../../types/async-iterable';

declare function asyncTakeLast<T>(iterable: AsyncWrappable<T>): Promise<T | undefined>;

export { asyncTakeLast };
