/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$deep-equal.d.ts#1643820505033
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
declare function deepEqual(...values: Array<any>): boolean;

declare function __deepEqual(
  iterables: Array<any>,
  same?: (a: any, b: any, depth: number) => boolean,
  coerceNil?: boolean,
): boolean;

export { __deepEqual, deepEqual };
