/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$is-empty.d.ts#1643820505043
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncWrappable } from '../../types/async-iterable';

declare function asyncIsEmpty(iterable: AsyncWrappable<any>): Promise<boolean>;

export { asyncIsEmpty };
