/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$take.test.ts#1643820505056
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { asyncTake } from 'iter-tools-es';
import { asyncWrap, asyncUnwrap } from '../../../test/async-helpers.js';

describe('asyncTake', () => {
  it('takes the first n values', async () => {
    expect(await asyncUnwrap(asyncTake(2, asyncWrap([1, 2, 3])))).toEqual([1, 2]);
  });
});
