/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$take.test.ts#1643820505056
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { take } from 'iter-tools-es';
import { wrap, unwrap } from '../../../test/helpers.js';

describe('take', () => {
  it('takes the first n values', () => {
    expect(unwrap(take(2, wrap([1, 2, 3])))).toEqual([1, 2]);
  });
});
