/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$find.d.ts#1643820505036
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncWrappable } from '../../types/async-iterable';

declare function asyncFind<T, S extends T>(
  predicate: (value: T, i: number) => value is S,
): (iterable: AsyncWrappable<T>) => Promise<S | undefined>;

declare function asyncFind<T>(
  predicate: (value: T, i: number) => boolean | Promise<boolean>,
): (iterable: AsyncWrappable<T>) => Promise<T | undefined>;

declare function asyncFind<T, S extends T>(
  predicate: (value: T, i: number) => value is S,
  iterable: AsyncWrappable<T>,
): Promise<S | undefined>;

declare function asyncFind<T>(
  predicate: (value: T, i: number) => boolean | Promise<boolean>,
  iterable: AsyncWrappable<T>,
): Promise<T | undefined>;

export { asyncFind };
