/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$find.d.ts#1643820505036
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Wrappable } from '../../types/iterable';

declare function find<T, S extends T>(
  predicate: (value: T, i: number) => value is S,
): (iterable: Wrappable<T>) => S | undefined;

declare function find<T>(
  predicate: (value: T, i: number) => boolean,
): (iterable: Wrappable<T>) => T | undefined;

declare function find<T, S extends T>(
  predicate: (value: T, i: number) => value is S,
  iterable: Wrappable<T>,
): S | undefined;

declare function find<T>(
  predicate: (value: T, i: number) => boolean,
  iterable: Wrappable<T>,
): T | undefined;

export { find };
