/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$compress.d.ts#1643820505030
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncWrappable, AsyncIterableIterator } from '../../types/async-iterable';

declare function asyncCompress<T>(
  source: AsyncWrappable<T>,
  included: AsyncWrappable<boolean>,
): AsyncIterableIterator<T>;

export { asyncCompress };
