/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$equal.d.ts#1643820505035
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Wrappable } from '../../types/iterable';

declare function equal(
  same: (a: any, b: any) => boolean,
): (...seqs: Array<Wrappable<any>>) => (iterable: Wrappable<any>) => boolean;

declare function equal(
  same: (a: any, b: any) => boolean,
  ...seqs: Array<Wrappable<any>>
): (iterable: Wrappable<any>) => boolean;

declare function equal(...seqs: Array<Wrappable<any>>): (iterable: Wrappable<any>) => boolean;

export { equal };
