/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$join-with.d.ts#1643820505044
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncWrappable, AsyncIterableIterator } from '../../types/async-iterable';

declare function asyncJoinWith<W, T>(
  separator: W,
  source: AsyncWrappable<AsyncWrappable<T>>,
): AsyncIterableIterator<T | W>;

declare function asyncJoinWith<W>(
  separator: W,
): <T>(source: AsyncWrappable<AsyncWrappable<T>>) => AsyncIterableIterator<T | W>;

export { asyncJoinWith };
