/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$join-with.d.ts#1643820505044
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Wrappable, IterableIterator } from '../../types/iterable';

declare function joinWith<W, T>(
  separator: W,
  source: Wrappable<Wrappable<T>>,
): IterableIterator<T | W>;

declare function joinWith<W>(
  separator: W,
): <T>(source: Wrappable<Wrappable<T>>) => IterableIterator<T | W>;

export { joinWith };
