/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$split-when.d.ts#1643820505051
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Wrappable, IterableIterator } from '../../types/iterable';

declare function splitWhen<T>(
  predicate: (value: T, i: number) => any,
): (source: Wrappable<T>) => IterableIterator<IterableIterator<T>>;

declare function splitWhen<T>(
  predicate: (value: T, i: number) => any,
  source: Wrappable<T>,
): IterableIterator<IterableIterator<T>>;

export { splitWhen };
