/* @macrome
 * @generatedby /generate/generators/impls/index.cjs
 * @generatedfrom ./$consume.js#1643820505031
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { asyncIterableCurry } from '../../internal/async-iterable.js';

export async function __asyncConsume(iterable) {
  /* eslint-disable */
  // prettier-ignore
  for await (const _ of iterable)
    {}
  /* eslint-enable */
}

export const asyncConsume = /*#__PURE__*/ asyncIterableCurry(__asyncConsume, {
  reduces: true,
});
