/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$consume.d.ts#1643820505031
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Wrappable } from '../../types/iterable';

declare function consume<T>(iterable: Wrappable<T>): void;

export { consume };
