/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$join.d.ts#1643820505044
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Wrappable, IterableIterator } from '../../types/iterable';

declare function join<T>(source: Wrappable<Wrappable<T>>): IterableIterator<T>;

export { join };
