/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$to-object.d.ts#1643820505058
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncWrappable } from '../../types/async-iterable';

declare function asyncToObject<V>(
  iterable: AsyncWrappable<[string, V]>,
  proto?: any,
): Promise<{ [key: string]: V }>;

export { asyncToObject };
