/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$some.d.ts#1643820505048
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncWrappable } from '../../types/async-iterable';

declare function asyncSome<T>(
  func: (value: T, i: number) => boolean | Promise<boolean>,
): (iterable: AsyncWrappable<T>) => Promise<boolean>;

declare function asyncSome<T>(
  func: (value: T, i: number) => boolean | Promise<boolean>,
  iterable: AsyncWrappable<T>,
): Promise<boolean>;

export { asyncSome };
