/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$some.d.ts#1643820505048
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Wrappable } from '../../types/iterable';

declare function some<T>(
  func: (value: T, i: number) => boolean,
): (iterable: Wrappable<T>) => boolean;

declare function some<T>(func: (value: T, i: number) => boolean, iterable: Wrappable<T>): boolean;

export { some };
