/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$take-last-or.d.ts#1643820505054
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncWrappable } from '../../types/async-iterable';

declare function asyncTakeLastOr<E, T>(whenEmpty: E, iterable: AsyncWrappable<T>): Promise<T | E>;

export { asyncTakeLastOr };
