/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$take-last-or.d.ts#1643820505054
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Wrappable } from '../../types/iterable';

declare function takeLastOr<E, T>(whenEmpty: E, iterable: Wrappable<T>): T | E;

export { takeLastOr };
