/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$to-array.d.ts#1643820505057
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Wrappable } from '../../types/iterable';

declare function toArray<T>(source: Wrappable<T>): Array<T>;

export { toArray };
