/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$tap.d.ts#1643820505057
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncWrappable, AsyncIterableIterator } from '../../types/async-iterable';

declare function asyncTap<T>(
  callback: (value: T, i: number) => any | Promise<any>,
): (source: AsyncWrappable<T>) => AsyncIterableIterator<T>;

declare function asyncTap<T>(
  callback: (value: T, i: number) => any | Promise<any>,
  source: AsyncWrappable<T>,
): AsyncIterableIterator<T>;

export { asyncTap };
