/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$tap.d.ts#1643820505057
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Wrappable, IterableIterator } from '../../types/iterable';

declare function tap<T>(
  callback: (value: T, i: number) => any,
): (source: Wrappable<T>) => IterableIterator<T>;

declare function tap<T>(
  callback: (value: T, i: number) => any,
  source: Wrappable<T>,
): IterableIterator<T>;

export { tap };
