/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$flat-map.d.ts#1643820505038
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncWrappable, AsyncIterableIterator } from '../../types/async-iterable';

declare function asyncFlatMap<O, T>(
  func: (value: T, i: number) => AsyncWrappable<O> | Promise<AsyncWrappable<O>>,
): (source: AsyncWrappable<T>) => AsyncIterableIterator<O>;

declare function asyncFlatMap<O, T>(
  func: (value: T, i: number) => AsyncWrappable<O> | Promise<AsyncWrappable<O>>,
  source: AsyncWrappable<T>,
): AsyncIterableIterator<O>;

export { asyncFlatMap };
