/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$size.d.ts#1643820505047
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { AsyncWrappable } from '../../types/async-iterable';

declare function asyncSize<Iter extends AsyncWrappable<any>>(
  iterable: Iter,
): Promise<Iter extends any[] ? Iter['length'] : number>;

export { asyncSize };
