/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$size.d.ts#1643820505047
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Wrappable } from '../../types/iterable';

declare function size<Iter extends Wrappable<any>>(
  iterable: Iter,
): Iter extends any[] ? Iter['length'] : number;

export { size };
