/* @macrome
 * @generatedby /generate/generators/types/index.cjs
 * @generatedfrom ./$cycle.d.ts#1643820505032
 * This file is autogenerated. Please do not edit it directly.
 * When editing run `npx macrome watch` then change the file this is generated from.
 */
import { Wrappable, IterableIterator } from '../../types/iterable';

declare function cycle<T>(source: Wrappable<T>): IterableIterator<T>;

export { cycle };
